export const GET_FILTER_ITEMS_SUCCESS = "GET_FILTER_ITEMS_SUCCESS";
export const GET_PORTFOLIO_ITEMS_SUCCESS = "GET_PORTFOLIO_ITEMS_SUCCESS";
export const LOAD_PORTFOLIO_MODAL = "LOAD_PORTFOLIO_MODAL";
export const OPEN_PORTFOLIO_MODAL = "OPEN_PORTFOLIO_MODAL";
export const CHANGE_MENU = "CHANGE_MENU";
